#!/usr/bin/env php
<?php

function findAutoloader()
{
    if (file_exists($path = __DIR__.'/../vendor/autoload.php'))
    {
        return $path;
    }   

    return __DIR__.'/../../../autoload.php';
}

require findAutoloader();

exit ((new Packer\Packer)->run());
